package ServerDS::Model::ServerDS_DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ServerDS_DB',
    
    connect_info => {
        dsn => 'dbi:mysql:serverds:localhost:3306',
        user => 'serverds',
        password => 'SdEfRrVsEsRfDgS',
    }
);

=head1 NAME

ServerDS::Model::ServerDS_DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ServerDS>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ServerDS_DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

linuxtech

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
